<input type="hidden" value="<?php echo $this->pageCount;?>" class="pageCount">
<?php if ($this->pageCount): ?>
     <div>
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                     <a href="#" class="prevArrow">
                         <<
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a class="prevArrow">
                         <<
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a class="nextPage">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li>
                         <a class="nextPage"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php  if($page >= 10):?>
                 <li>
                     <a class='arrow'>
                         >>
                     </a>
                    
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         >>
                     </a>
                 </li>
             <?php endif; ?>
                
         </ul>
     </div>
 <?php endif; ?>