<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- dialog body -->
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        Are you Sure??
      </div>
      <!-- dialog buttons -->
      <div class="modal-footer">
      <button type="button" class="btn btn-primary" id="okModalForm">Ok</button>
      <button type="button" data-dismiss="modal" class="btn btn-danger" id="cancel">Cancel</button>
      </div>
    </div>
  </div>
</div>