<!-- head section -->
        <section class="content-top-margin page-title page-title-small border-bottom-light border-top-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 wow fadeInUp" data-wow-duration="300ms">
                        <!-- page title -->
                        <h1 class="black-text">About Us</h1>
                        <!-- end page title -->
                    </div>
                    <div class="col-md-4 col-sm-12 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">

                    </div>
                </div>
            </div>
        </section>
        <!-- end head section -->

        <!-- content section -->
       <!-- content section -->
        <section class="wow fadeIn cover-background" style="background-image:url('images/about.jpg');">
            <div class="opacity-medium bg-dark-gray"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-5 col-sm-8 center-col text-center position-relative">
                        <p class="title-med text-uppercase letter-spacing-1 white-text font-weight-600 wow fadeInDown">We Work Day and Night<br> To deliver Quality to you</p>

                    </div>
                </div>
            </div>
        </section>
        <!-- testimonial section -->
        <section class="wow fadeIn">
            <div class="container">
                <div class="row">
                    <!-- testimonials item -->
                    <div class="col-md-4 col-sm-4 testimonial-style2 text-center wow fadeInUp xs-margin-bottom-ten">
                        <img src="http://placehold.it/300x300" alt=""/>
                        <p class="center-col width-90">Will definetely order again . Love the concept . Now I dont have to waste money on one time wear . Thanks Aufre !!</p>
                        <span class="name black-text">Niharika Sharma</span>
                        <i class="fa fa-quote-left small-icon yellow-text display-block margin-five no-margin-bottom"></i>
                    </div>
                    <!-- end testimonials item -->
                    <!-- testimonials item -->
                    <div class="col-md-4 col-sm-4 testimonial-style2 text-center wow fadeInUp xs-margin-bottom-ten">
                        <img src="http://placehold.it/300x300" alt=""/>
                        <p class="center-col width-90">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
                        <span class="name black-text">Herman Miller</span>
                        <i class="fa fa-quote-left small-icon yellow-text display-block margin-five no-margin-bottom"></i>
                    </div>
                    <!-- end testimonials item -->
                    <!-- testimonials item -->
                    <div class="col-md-4 col-sm-4 testimonial-style2 text-center wow fadeInUp no-margin-top">
                        <img src="http://placehold.it/300x300" alt=""/>
                        <p class="center-col width-90">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>
                        <span class="name black-text">Bryan Jonhson </span>
                        <i class="fa fa-quote-left small-icon yellow-text display-block margin-five no-margin-bottom"></i>
                    </div>
                    <!-- end testimonials item -->
                </div>
            </div>
        </section>
        <!-- end testimonial section -->
        <section class="parallax1 parallax-fix no-padding parallax-gray-bg wow fadeIn">
            <img class="parallax-background-img" src="images/about.jpg" alt="" />
            <div class="container-fluid no-padding">
                <div class="row">
                    <div class="col-md-6 col-sm-12 pull-right bg-yellow padding-seven xs-padding-eight">
                        <h1 class="white-text">A bit of<br> History</h1>
                        <p class="text-med width-70 margin-five black-text no-margin-bottom md-full-width">Aufre.com was created to provide you an Endless Wardrobe . Got too many parties to attend ? Hate to repeat ? Wanna Look Gorgeous every single time ? If yes , You are in the right place</p>
                        <p class="text-med width-70 black-text margin-five md-full-width">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

                    </div>
                </div>
            </div>
        </section>

        <section class="wow fadeIn">
            <div class="container">
                <div class="row">
                    <!-- call to action -->
                    <div class="col-md-7 col-sm-12 text-center center-col">
                        <p class="title-large text-uppercase letter-spacing-1 black-text font-weight-600 wow fadeIn">Got any Questions
						? Want any new feature ?</p>
                        <a href="contact-us.html" class="highlight-button-black-border btn margin-six wow fadeInUp">Contact Us</a>
                    </div>
                    <!-- end call to action -->
                </div>
            </div>
        </section>
