<!-- head section -->
        <section class="content-top-margin page-title page-title-small bg-gray">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 wow fadeInUp" data-wow-duration="300ms">
                        <!-- page title -->
                        <h1 class="black-text">How It Works</h1>
                        <!-- end page title -->
                    </div>
                    <div class="col-md-4 col-sm-12 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">
                        <!-- breadcrumb -->

                        <!-- end breadcrumb -->
                    </div>
                </div>
            </div>
        </section>
        <!-- end head section -->

        <!-- content section -->
        <section class="wow fadeIn">

                <img src="images/bannerf2.jpg"/>


        </section>
		<!-- How why and what Section -->
		<section class="wow fadeIn">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 center-col">
                        <!-- tab -->
                        <div class="tab-style1">
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <!-- tab navigation -->
                                    <ul class="nav nav-tabs nav-tabs-light text-center height-auto">
                                        <li class="active"><a href="#tab_sec1" data-toggle="tab">What We do </a></li>
                                        <li><a href="#tab_sec2" data-toggle="tab">How we do it </a></li>
                                        <li><a href="#tab_sec3" data-toggle="tab">Why we do it </a></li>
                                    </ul>
                                    <!-- tab end navigation -->
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="wide-separator-line no-margin-lr"></div>
                                </div>
                            </div>
                            <!-- tab content section -->
                            <div class="tab-content">
                                <!-- tab content -->
                                <div class="tab-pane med-text fade in active" id="tab_sec1">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-12 text-left gray-text">
                                            <p class="text-large margin-right-ten">We provide you high end fashion clothes and accessories on Rent We have a beutiful collection of designer Wears and Party Dresses</p>
                                        </div>
                                        <div class="col-md-6 col-sm-12 text-left text-med gray-text">
                                            <p class="text-uppercase">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text.</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12">
                                            <div class="wide-separator-line no-margin-lr"></div>
                                        </div>
                                    </div>
                                      <div class="row">
                                        <div class="col-md-12 col-sm-12 text-center service-year black-text">
                                            <strong>Fashion On rent</strong>
                                        </div>
                                    </div>
                                </div>
                                <!-- end tab content -->
                                <!-- tab content -->
                                <div class="tab-pane fade in" id="tab_sec2">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-12 text-left gray-text">
                                            <p class="text-large margin-right-ten">The Image Above Explains Our Whole Process . We work day and Night to increase our Quality of Products and Services</p>
                                        </div>
                                        <div class="col-md-6 col-sm-12 text-left text-med gray-text">
                                            <p class="text-uppercase">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text.</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="wide-separator-line"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 text-center service-year black-text">
                                            <strong>CHoose --> Wear --> Return </strong>
                                        </div>
                                    </div>
                                </div>
                                <!-- end tab content -->
                                <!-- tab content -->
                                <div class="tab-pane fade in" id="tab_sec3">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-12 text-left gray-text">
                                            <p class="text-large margin-right-ten"> We belive that fashionistas like you should never repeat the same dress twice . Keeing that in mind , Why to spend a lot of money on buying dresses you will never wear again ? . Simply rent it out .  Sounds Good . We also think so , That is why we do it . </p>
                                        </div>
                                        <div class="col-md-6 col-sm-12 text-left text-med gray-text">
                                            <p class="text-uppercase">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text.</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="wide-separator-line"></div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 text-center service-year black-text">
                                            <strong>It is not about owning the dress . It is all about owning the look </strong>
                                        </div>
                                    </div>
                                </div>
                                <!-- end tab content -->
                            </div>
                            <!-- end tab content section -->
                        </div>
                        <!-- end tab -->
                    </div>
                </div>
            </div>
        </section>

		<!-- end How why and what Section  -->


		 <section class="wow fadeIn">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 col-sm-10 no-padding-top no-padding-bottom testimonial-style2 center-col text-center position-relative">
                        <i class="fa fa-quote-left medium-icon black-text margin-five no-margin-top"></i>
                        <h6 class="black-text">Always Dress Like you're going to see your worst enemy</h6>
                        <span class="name black-text">Kimora Lee</span>
                    </div>
                </div>
            </div>
        </section>
		
