<!-- head section -->
        <section class="content-top-margin page-title page-title-small border-bottom-light border-top-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 wow fadeInUp" data-wow-duration="300ms">
                        <!-- page title -->
                        <h1 class="black-text">RENT VIA US</h1>
                        <!-- end page title -->
                    </div>
                    <div class="col-md-4 col-sm-12 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">

                    </div>
                </div>
            </div>
        </section>
        <!-- end head section -->

        <!-- content section -->
        <section class="bg-black wow fadeIn">
            <div class="container">
                <div class="row team-size-main sm-no-margin">
                    <!-- team counter -->
                    <div class="col-md-2 col-sm-3 text-center wow fadeIn xs-margin-bottom-seven">
                        <div class="team-size text-uppercase white-text"><span class="clearfix">1</span><br>Rent Your Clothes , Bags you do not wish to repeat</div>
                    </div>
                    <!-- end team counter -->
                    <!-- team counter plus -->
                    <div class="col-md-1 col-sm-1 text-center wow fadeIn xs-display-none">
                        <div class="team-plus text-uppercase"><span class="clearfix">+</span></div>
                    </div>
                    <!-- end team counter plus -->
                    <!-- team counter -->
                    <div class="col-md-2 col-sm-2 text-center wow fadeIn xs-margin-bottom-seven">
                        <div class="team-size text-uppercase white-text"><span class="clearfix">2 </span><br> We will pickup from your Home <br> No Hassles <br> No Worries</span></div>
                    </div>
                    <!-- end team counter -->
                    <!-- team counter plus -->
                    <div class="col-md-1 col-sm-1 text-center wow fadeIn xs-display-none">
                        <div class="team-plus text-uppercase"><span class="clearfix">+</span></div>
                    </div>
                    <!-- end team counter plus  -->
                    <!-- team counter -->
                    <div class="col-md-2 col-sm-2 text-center wow fadeIn xs-margin-bottom-seven">
                        <div class="team-size text-uppercase white-text"><span class="clearfix">3</span><br>Earn Cash whenever your clothes are rented by Others</div>
                    </div>
                    <!-- end team counter  -->
                    <!-- team counter plus  -->
                    <div class="col-md-1 col-sm-1 text-center wow fadeIn xs-display-none">
                        <div class="team-plus text-uppercase"><span class="clearfix">+</span></div>
                    </div>
                    <!-- end team counter plus  -->
                    <!-- team counter -->
                    <div class="col-md-2 col-sm-2 text-center wow fadeIn">
                        <div class="team-size text-uppercase white-text"><span class="clearfix">4</span><br>Earn Store Credits upto Rs 1000</div>
                    </div>
                    <!-- end team counter -->
                </div>
            </div>
        </section>
        <section class="wow fadeIn">
            <div class="container">


                <div class="row">
                    <div class="col-md-6 col-sm-10 col-xs-11 center-col login-box">
                        <!-- form title  -->
                        <h2>RENT VIA US</h2>
                        <!-- end form title  -->

                        <div class="separator-line bg-black no-margin-lr margin-zero"></div>
                        <form>
                            <div class="form-group no-margin-bottom">
                                <!-- label  -->
                                <label for="name" class="text-uppercase">Name *</label>
                                <!-- end label  -->
                                <!-- input  -->
                                <input type="text" name="name" id="name">
                                <!-- end input  -->
                            </div>
                            <div class="form-group no-margin-bottom">
                                <!-- label  -->
                                <label for="Email" class="text-uppercase">Email ID *</label>
                                <!-- end label  -->
                                <!-- input  -->
                                <input type="text" name="email" id="email">
                                <!-- end input  -->
                            </div>
							 <div class="form-group no-margin-bottom">
                                <!-- label  -->
                                <label for="Phone" class="text-uppercase">Phone No. *</label>
                                <!-- end label  -->
                                <!-- input  -->
                                <input type="text" name="phone" id="phone">
                                <!-- end input  -->
                            </div>
							 <div class="form-group no-margin-bottom">
                                <!-- label  -->
                                <label for="Brand" class="text-uppercase">BRand of Dress</label>
                                <!-- end label  -->
                                <!-- input  -->
                                <input type="text" name="brand" id="brand">
                                <!-- end input  -->
                            </div>
							  <div class="form-group">
                                <!-- label -->
                                <label class="text-uppercase">You Are *</label>
                                <!-- end label -->
                                <!-- select -->
                                <div class="select-style input-round big-input">
                                    <select>
                                        <option value="">Individual</option>
                                        <option value="">Shop</option>
                                        <option value="">Designer</option>
                                        <option value="">Secret Ninja</option>
                                    </select>
                                </div>
                                <!-- end select -->
                            </div>
                            <div class="form-group">
                                <!-- label  -->
                                <label for="InputFile">IMAGE</label>
                                <!-- end label  -->
                                <!-- input  -->
                                <input type="file" id="InputFile" class="input-round big-input text-lowercase">
                                <!-- end input  -->
                            </div>
                            <!-- button  -->
                            <button class="btn btn-black no-margin-bottom btn-small btn-round no-margin-top" type="submit">Submit</button>
                            <!-- end button  -->
                        </form>
                    </div>
                </div>
            </div>
        </section>
