<?php
    foreach($products as $product) {
?>
<!-- shop item -->
    <div class="col-md-6 col-sm-6">
        <div class="home-product text-center position-relative overflow-hidden margin-ten no-margin-top">
             <a href="shop-single-product.html"><img src="http://www.tattooset.com/images/tattoo/2012/05/31/3920-clothing-fashion-tattoo-photography-style-favim_large.jpg" alt=""/></a>
             <br><br>
            <span class="product-name text-uppercase"><a href="shop-single-product.html"><?php echo $product['aufriProductsName']; ?></a></span>
            <span class="price black-text"><span>&#8377;&nbsp;</span><?php echo $product['aufriProductsRent']; ?></span>
            <div class="quick-buy">
                <div class="product-share">
                    <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                    <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                    <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                </div>
            </div>
        </div>
    </div>
<!-- end shop item -->
<?php } ?>
