<section>
            <div class="container">
                <div class="row">
                    <!-- sidebar  -->
                    <div class="col-md-2 col-sm-4 sidebar">
                        <!-- widget  -->
                        <div class="widget">
                            <h5 class="widget-title font-alt">Categories</h5>
                            <div class="thin-separator-line bg-dark-gray no-margin-lr margin-ten"></div>
                            <div class="widget-body">
                                <ul class="category-list">
                                    <?php
                                        foreach($subCategories as $subCategory) {
                                    ?>
                                        <li <?php if($subCategory['aufriProductSubcategoryName'] == $prevoius['subCategoryName']) {?>
                                            class="active" <?php } ?>>
                                            <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                            'subCategory' => $prevoius['subCategory'],'subCategoryName' => $subCategory['aufriProductSubcategoryName'],
                                            'categoryId' => $subCategory['aufriProductSubcategoryId'])); ?>">
                                                <?php echo $subCategory['aufriProductSubcategoryName']?>
                                            </a>
                                        </li>
                                    <?php
                                        }
                                    ?>
                                </ul>
                            </div>
                        </div>
                        <!-- end widget  -->
                                                <!-- widget  -->
                        <div class="widget">
                            <h5 class="widget-title font-alt">Shop By Size</h5>
                            <div class="thin-separator-line bg-dark-gray no-margin-lr margin-ten"></div>
                            <div class="widget-body">
                                <ul class="size clearfix">
                                    <li <?php if($prevoius['size'] == 'ALL') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'ALL')); ?>">ALL</a>
                                    </li>
                                    <li <?php if($prevoius['size'] == 'S') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'S')); ?>">S</a>
                                    </li>
                                    <li <?php if($prevoius['size'] == 'M') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'M')); ?>">M</a>
                                    </li>
                                    <li <?php if($prevoius['size'] == 'L') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'L')); ?>">L</a>
                                    </li>
                                    <li <?php if($prevoius['size'] == 'XL') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'XL')); ?>">XL</a>
                                    </li>
                                    <li <?php if($prevoius['size'] == 'XXL') {?> class="active" <?php } ?>>
                                        <a href="<?php echo $this->url('category_landing', array('category' => $prevoius['category'],
                                        'subCategory' => $prevoius['subCategory'],'subCategoryName' => $prevoius['subCategoryName'],
                                        'categoryId' => $prevoius['categoryId'], 'size' => 'XXL')); ?>">XXL</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- end widget  -->
                        <!-- widget  -->
                        <!-- end widget  -->
                    </div>
                    <!-- end sidebar  -->
                    <div class="col-md-9 col-sm-8 col-md-offset-1">
                        <div class="shorting clearfix xs-margin-top-three">
                            <div class="col-md-8 col-sm-7 grid-nav">
                                <a href="shop-with-sidebar-list.html"><i class="fa fa-bars"></i></a>
                                <a href="shop-with-sidebar.html"><i class="fa fa-th"></i></a>
                                <p class="text-uppercase letter-spacing-1 sm-display-none">
                                    Home > <?php echo $prevoius['category'].' > '.$prevoius['subCategory'].' > '.$prevoius['subCategoryName'].' > '.$prevoius['size']; ?>
                                </p>
                            </div>
                            <div class="col-md-3 col-sm-5 pull-right">
                                <div class="select-style input-round med-input shop-shorting no-border">
                                    <select class="sortProduct" id="sortProduct" data-attr-category-id="<?php echo $prevoius['categoryId']; ?>"
                                        data-attr-category="<?php echo $prevoius['category']; ?>" data-attr-subcategory="<?php echo $prevoius['subCategory']; ?>"
                                        data-attr-subcategory-name="<?php echo $prevoius['subCategoryName']; ?>" data-attr-size="<?php echo $prevoius['size']; ?>">
                                        <option value="">Select sort by</option>
                                        <option value="popular">By popularity</option>
                                        <option value="asc">Price: low to high</option>
                                        <option value="desc">Price: high to low</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="product-listing margin-three" id="ajaxSortProducts">
                            <?php
                                echo $this->partial('ajax-product-sort',
                                        array('products' => $products, 'prevoius' => $prevoius));
                                ?>
                        </div>

                    </div>
                </div>
            </div>
        </section>
