<?php
echo $this->partial('menu', array('active' => 'products'));
?>
<div class="container pd20">
    <div class="panel panel-info col-md-12 pd20">
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-3">
                    <label> Name</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php echo wordwrap($coupon->getCouponName(), 65, "<br>\n", true); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Code </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5 word-wrap">
                    <?php echo $coupon->getCouponCode(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Start Date</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php
                        echo $coupon->getCouponStartdate();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>End Date </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponEnddate(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Discount </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponDiscount(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Avail For </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponAvailFor(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Minimum Order </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponMinorder(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Coupon Type</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponType(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Coupon count for any customer </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponCountForAnyCustomer(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Coupon count for single customer </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $coupon->getCouponForSingleCustomer(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row col-md-3 col-md-offset-4">
    <a href="<?php echo $this->url('admin_view_coupons');?>" class="btn btn-primary btnWidth">Back</a>
    <a href="<?php echo $this->url('admin_edit_coupons', array('id' => $coupon->getCouponId()));?>"
       class="btn btn-warning btnWidth">Edit</a>

</div>
