<div class="alert alert-dismissable alert-danger tour hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><ul><li></li></ul></div>
<?php echo $this->partial('menu', array('active' => 'tour')); ?>
<div class="row addButtonClass">
    <div class="col-sm-5">
        <a class="margin10"
           href="<?php echo $this->url('admin_add_coupons'); ?>">
            <button class="btn-primary btn">Add Coupon</button>
        </a>
    </div>
    <div class="col-sm-5">
        <form action="#" method="post">
            <input type="text" name="couponCode" class="form-control col-sm-8" Placeholder="Search by coupon code"  style="width:50%; margin-right: 10px">
            <input type="submit" value="Search" class="col-sm-4 btn-primary btn">
        </form>
    </div>
</div>
<div class="row itineraryRowHeading">
    <div class="col-sm-12 itineraryHeading">
        <div class="col-sm-3 noPadding">Coupon Name</div>
        <div class="col-sm-2 noPadding">Coupon Code</div>
        <div class="col-sm-1 noPadding">Coupon StartDate</div>
        <div class="col-sm-1 noPadding">Coupon EndDate</div>
        <div class="col-sm-1 noPadding">Coupon Discount</div>
        <div class="col-sm-4 alignCenter">Action</div>
    </div>
</div>
<div class="">
    <?php
    $i = 1;
    if (count($this->coupons) > 0) {
        foreach ($this->coupons as $coupon) {
            ?>
            <div class="row attractionList widthNarrow ">
                <div class="col-sm-12 post itineraryList <?php if($i%2==0) {echo "greyColor";}?>">
                    <div class="col-sm-3 attrName"><?php echo $coupon['aufriCouponsName']; ?></div>
                    <div class="col-sm-2 noPadding"><?php echo $coupon['aufriCouponsCode']; ?> </div>
                    <div class="col-sm-1 noPadding"><?php echo $coupon['aufriCouponsStartdate']; ?> </div>
                    <div class="col-sm-1 noPadding"><?php echo $coupon['aufriCouponsEnddate']; ?> </div>
                    <div class="col-sm-1 noPadding"><?php echo $coupon['aufriCouponsDiscount']; ?> </div>
                    <div class="col-sm-4">
                        <a class="margin25" href="<?php echo $this->url('admin_showdetails_coupons', array('id' => $coupon['aufriCouponsId'])) ?>">
                            <button type="button" class="btn btn-success btnWidth" role="button">View</button></a>
                        <a href="<?php echo $this->url('admin_edit_coupons', array('id' => $coupon['aufriCouponsId'])) ?>">
                            <button type="button" class="btn btn-warning btnWidth">Edit</button></a>
                        <a href="<?php echo $this->url('admin_delete_coupons', array('id' => $coupon['aufriCouponsId'])) ?>">
                            <button type="button" class="btn btn-danger btnWidth">Delete</button></a>
                    </div>
                </div>
            </div>
            <?php $i++;
        }
    } else {
        ?>
        <div class="row pd5">
            <div class="col-sm-12">No Coupons To Display</div>
        </div>
        <?php
    }
    ?>
</div>
