<!-- end head section -->


<section class="wow fadeIn">
    <div class="container">


        <div class="row">
            <div class="col-md-6 col-sm-10 col-xs-11 center-col login-box">
                <!-- form title  -->
                <h2>Login </h2>
                <!-- end form title  -->

                <div class="separator-line bg-black no-margin-lr margin-zero"></div>
                <form action="<?php echo $this->url('login');?>" method="post">
                    <div class="form-group no-margin-bottom">
                        <!-- label  -->
                        <label for="username" class="text-uppercase" color="#449d44"><b>Email</b></label>
                        <!-- end label  -->
                        <!-- input  -->
                        <input type="text" name="email" id="username" class="input-round big-input">
                        <!-- end input  -->
                    </div>
                    <div class="form-group no-margin-bottom">
                        <!-- label  -->
                        <label for="password" class="text-uppercase"><b>Password</b></label>
                        <!-- end label  -->
                        <!-- input  -->
                        <input type="password" name="password" id="password" class="input-round big-input">
                        <!-- end input  -->
                    </div>

                    <button class="btn highlight-button-dark btn-small btn-round margin-five no-margin-right" type="submit">Login</button>
                       <!-- <a href="login.html" class="display-block text-uppercase">Forgot Password ?</a> -->
					   <a href="<?php echo $this->url('register'); ?>" class="display-block text-uppercase" color="#449d44">
                           New User - Sign Up
                       </a>
                    </form>


                </form>
            </div>
        </div>
    </div>
</section>
