<?php
/**
* Login page to login through email id and password
* @author Deepika Verma <deepika.verma@optimusinfo.com>
*/
$form->setAttribute('action', $this->url('auth', array('action' => 'login')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="container">
    <div id="loginbox" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info" >
            <div class="panel-heading">
                <div class="panel-title">Sign In</div>
            </div>

            <div class="panel-body" >

                <div class="pd10">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user"></i>
                    </span>
                    <?php echo $this->formElement($form->get('email')); ?>
                </div>
                <span class="alert-danger">
                    <?php echo $this->formElementerrors($form->get('email')); ?>
                </span>
                </div>

                <div class="pd10">
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user"></i>
                    </span>
                    <?php echo $this->formElement($form->get('password')); ?>
                </div>
                <span class="alert-danger">
                    <?php echo $this->formElementerrors($form->get('password')); ?>
                </span>
                </div>
                <div class="col-md-3 col-md-offset-9">
                    <?php echo $this->formRow($form->get('submit')); ?>

                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
