<!-- head section -->
<section class="content-top-margin page-title page-title-small border-bottom-light border-top-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-7 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">
                <!-- breadcrumb -->
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#"><?php echo $prevoius['category']; ?></a></li>
                    <li><a href="#"><?php echo $prevoius['subCategory']; ?></a></li>
                    <li><a href="#"><?php echo $prevoius['subCategoryName']; ?></a></li>
                </ul>
                <!-- end breadcrumb -->
            </div>
            <div class="col-md-4 col-sm-5 wow fadeInUp header-nav text-right sm-margin-top-two" data-wow-duration="300ms">
                <!-- next/previous -->
                <!-- end next/previous -->
            </div>
        </div>
    </div>
</section>
<!-- end head section -->

<!-- content section -->
<section>
    <div class="container">
        <div class="row">
            <!-- product images -->
            <div class="col-md-6 col-sm-12 zoom-gallery sm-margin-bottom-ten">
                <a href="http://placehold.it/700x583"><img src="http://placehold.it/700x583" alt=""/></a>
                <div class="products-thumb text-center">
                    <a href="http://placehold.it/700x583"><img src="http://placehold.it/700x583" alt=""/></a>
                    <a href="http://placehold.it/700x583"><img src="http://placehold.it/700x583" alt=""/></a>
                    <a href="http://placehold.it/700x583"><img src="http://placehold.it/700x583" alt=""/></a>
                </div>
            </div>
            <!-- end product images -->
            <div class="col-md-5 col-sm-12 col-md-offset-1">

                <!-- product name -->
                <span class="product-name-details text-uppercase font-weight-600 letter-spacing-2 black-text">FUSCHIA SARI WITH GOLD DABKA BORDER</span>
                <!-- end product name -->
                <!-- product stock -->
                <p class="text-uppercase letter-spacing-2 margin-two"><mark class="label-success white-text">In Stock / Free Shipping / Dry Cleaned and Ironed</mark></p>
                <!-- end product stock -->
                <div class="separator-line bg-black no-margin-lr margin-five"></div>
                <!-- product short description -->
              <p>This silk crepe stunner is set apart by its wide border in Jade's signature gold dabka work. It's a striking gorgeous pink shade which is lifted by the aroyal blue lining and trim on the border. You'll never blend in with this one.  Enough said.</p>
                <!-- end product short description -->
                <span class="price black-text"><del>Retail : 7000</del><h2>Rent: 750</h2></span>
                <div>
                    <!-- product color -->
                    <br>
                    <!-- end product color -->
                    <!-- product size -->
                    <ul class="size clearfix size-details">
                        <li class="active"><a href="#">S</a></li>
                        <li><a href="#">M</a></li>
                        <li><a href="#">L</a></li>
                        <li class="size-chart"><a href="#">Size Chart</a></li>
                    </ul>
                    <!-- end product size -->
                    <br>
                    <h5> Enter Your Event Date:</h5>


                </div>

                <div class="col-md-9 col-sm-9 no-padding margin-five">
                    <!-- add to bag button -->
                    <a class="highlight-button-dark btn btn-medium button" href="shop-cart.html"><i class="icon-basket"></i> Add To Cart</a>
                    <!-- end add to bag button -->
                </div>

             <div class="col-md-8 col-sm-9 product-details-social no-padding">

                         <!-- modal popup #2 -->



                <a class="highlight-button btn btn-small no-margin-right popup-with-zoom-anim no-margin-bottom" href="#modal-popup2">Contact Us</a>
                <!-- modal popup -->
                <div id="modal-popup2" class="zoom-anim-dialog mfp-hide col-lg-3 col-md-6 col-sm-7 col-xs-11 center-col bg-white text-center modal-popup-main">
                    <span class="slider-subtitle5 black-text no-margin-bottom">Contact Us </span>
                    <p class="margin-four">  <i class="icon-mobile"></i>
Call/ WhatsApp: <mark class="label-success white-text">9972303048</mark></p>
                    <p class="margin-four"><i class="icon-happy"></i>Mail Us : <mark class="label-success white-text">hello@aufre.com</mark></p>
                    <a class="highlight-button btn btn-very-small button popup-modal-dismiss no-margin" href="#">Dismiss</a>
                </div>
                <!-- end modal popup -->


                         <!-- modal popup #2 -->


                &nbsp&nbsp&nbsp
                <a class="highlight-button btn btn-small no-margin-right popup-with-zoom-anim no-margin-bottom" href="#modal-popup3">Read Our FAQ</a>
                <!-- modal popup -->
                <div id="modal-popup3" class="zoom-anim-dialog mfp-hide col-lg-3 col-md-6 col-sm-7 col-xs-11 center-col bg-white text-center modal-popup-main">
                    <span class="slider-subtitle5 black-text no-margin-bottom">FAQ</span>
                    <p class="margin-four">1. Lorem Ipsum </p>
                    <a class="highlight-button btn btn-very-small button popup-modal-dismiss no-margin" href="#">Dismiss</a>
                </div>
                <!-- end modal popup -->


              </div>

            </div>
        </div>
    </div>
</section>



<section class="border-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h3 class="section-title">Recommended By Aufre</h3>
            </div>
        </div>
        <div class="row">
            <!-- related products slider -->
            <div id="shop-products" class="owl-carousel owl-theme dark-pagination owl-no-pagination owl-prev-next-simple">
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Richard Nicoll</a></span>
                        <span class="price black-text">$680</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Roland Mouret</a></span>
                        <span class="price black-text">$980</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Preen Line</a></span>
                        <span class="price black-text">$750</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Balmain</a></span>
                        <span class="price black-text">$350</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Dolce & Gabbana</a></span>
                        <span class="price black-text">$700</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
                <!-- shop item -->
                <div class="item">
                    <div class="home-product text-center position-relative overflow-hidden">
                        <a href="shop-single-product.html"><img src="http://placehold.it/600x500" alt=""/></a>
                        <span class="product-name text-uppercase"><a href="shop-single-product.html">Valentino</a></span>
                        <span class="price black-text">$370</span>
                        <div class="quick-buy">
                            <div class="product-share">
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Wishlist"><i class="fa fa-heart-o"></i></a>
                                <a href="#" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Compare"><i class="fa fa-refresh"></i></a>
                                <a href="shop-cart.html" class="highlight-button-dark btn btn-small no-margin-right quick-buy-btn" title="Add to Cart"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end shop item -->
            </div>
            <!-- end related products slider -->
        </div>
    </div>
</section>
<!-- end content section -->
