<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('Travelopod Portal')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0')
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css')
->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.min.css')
->prependStylesheet($this->basePath() . '/bootstrap/css/datepicker.css')
->prependStylesheet($this->basePath() . '/css/style.css')
->prependStylesheet($this->basePath() . '/css/ie.css', 'text/css', array('conditional' => 'lt IE 9',))
?>

<!-- Scripts -->
<?php echo $this->headScript()
->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js')
->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
->prependFile($this->basePath() . '/bootstrap/js/bootstrap-datepicker.js')

//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
</head>
<body>
	<div id="wrap">
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container-fluid">
					<span class="brand"><?=$this->layout()->getVariable('params')['email.program.name']?>
					</span>
				</div>
			</div>
		</nav>

		<div class="container-fliud">
			<?php echo $this->content; ?>
		</div>
	</div>
	<div class="container-fluid">
		<footer id="footer">
			<div class="row-fluid">
				<div class="span6">
					<p>
						&copy;
						<?=date('Y')?>
						OptimusInfo
					</p>
				</div>
				<!--/span-->
				<div class="span6">
					<p class="text-right">
						Travelopod<sup>&trade;</sup> Portal v1.0
					</p>
				</div>
				<!--/span-->
			</div>
			<!--/row-->
		</footer>
	</div>
	<?php echo $this->inlineScript() ?>
	<script src="/js/js-webshim-min/polyfiller.js"></script>
	<script>
            $.webshims.polyfill('forms');
        </script>
</body>
</html>
