<div class="alert alert-dismissable alert-danger tour hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><ul><li></li></ul></div>
<?php echo $this->partial('menu', array('active' => 'tour')); ?>
<div class="row">

    <div class="col-md-12">
        <h3>UPDATE ORDER</h3>
    </div>
    <form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
        <div class="col-md-12">
            <span class="col-md-1">
                <label>Order id</label>
            </span>
            <span class="col-md-2">
                <input type="text" class="form-control" value="" readonly="readonly">
            </span>
            <span class="col-md-1">
                <label>Status</label>
            </span>
            <span class="col-md-2">
                <select class="form-control" name="order-status">
                    <option value="New order">New order</option>
                    <option value="Ready">Ready</option>
                    <option value="Shipped">Shipped</option>
                    <option value="Delivered">Delivered</option>
                </select>
            </span>
        </div>
        <div class="col-md-12">
            <input type="submit" class="btn btn-success" value="Update"/>
        </div>
    </form>
</div>
