<div class="alert alert-dismissable alert-danger tour hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><ul><li></li></ul></div>
<?php echo $this->partial('menu', array('active' => 'tour')); ?>
<div class="row itineraryRowHeading">
    <div class="col-sm-12 itineraryHeading">
        <div class="col-sm-1 noPadding">Order Id</div>
        <div class="col-sm-1 noPadding">Order Date</div>
        <div class="col-sm-1 noPadding">Order Status</div>
        <div class="col-sm-1 noPadding alignCenter">Product Name</div>
        <div class="col-sm-1 noPadding alignCenter">Product Rent</div>
        <div class="col-sm-1 noPadding alignCenter">Product Deposit</div>
        <div class="col-sm-1 noPadding alignCenter">Shoppkeepr Name</div>
        <div class="col-sm-1 noPadding alignCenter">User Name</div>
        <div class="col-sm-1 noPadding alignCenter">User Address</div>
        <div class="col-sm-1 noPadding alignCenter">User PhoneNo</div>
        <div class="col-sm-1 noPadding alignCenter">Coupon code</div>
        <div class="col-sm-1 noPadding alignCenter">Coupon Discount</div>
    </div>
</div>
