<div class="alert alert-dismissable alert-danger tour hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><ul><li></li></ul></div>
<?php echo $this->partial('menu', array('active' => 'tour')); ?>
<div class="row itineraryRowHeading">
    <div class="col-sm-12 itineraryHeading">
        <div class="col-sm-1 noPadding">Order Id</div>
        <div class="col-sm-1 noPadding">Order Date</div>
        <div class="col-sm-1 noPadding">Order Status</div>
        <div class="col-sm-1 noPadding alignCenter">Product Name</div>
        <div class="col-sm-1 noPadding alignCenter">Product Rent</div>
        <div class="col-sm-1 noPadding alignCenter">Product Deposit</div>
        <div class="col-sm-1 noPadding alignCenter">Shoppkeepr Name</div>
        <div class="col-sm-1 noPadding alignCenter">User Name</div>
        <div class="col-sm-1 noPadding alignCenter">User Address</div>
        <div class="col-sm-1 noPadding alignCenter">User PhoneNo</div>
        <div class="col-sm-1 noPadding alignCenter">Coupon code</div>
        <div class="col-sm-1 noPadding alignCenter">Coupon Discount</div>
    </div>
</div>
<div class="">
    <?php
    $i = 1;
    if (count($this->orderList) > 0) {
        foreach ($this->orderList as $orderList) {
            ?>
            <div class="row attractionList widthNarrow ">
                <div class="col-sm-12 post itineraryList <?php if($i%2==0) {echo "greyColor";}?>">
                    <div class="col-sm-1 noPadding alignCenter">
                        <a href="<?php echo $this->url('admin_edit_orders', array('id' => $orderList['orderId'])) ?>">
                            <?php echo $orderList['orderId']; ?>
                        </a>
                    </div>
                    <div class="col-sm-1 noPadding"><?php echo $orderList['orderDate']; ?></div>
                    <div class="col-sm-1 noPadding"><?php echo $orderList['orderStatus']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter">
                        <a href="<?php echo $this->url('admin_showdetails_products', array('id' => $orderList['productId'])) ?>">
                            <?php echo $orderList['productName']; ?>
                        </a>
                    </div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['productRent']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['productDeposit']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter">
                        <a href="<?php echo $this->url('admin_showdetails_shopkeepers', array('id' => $orderList['shopkeeperId'])) ?>">
                            <?php echo $orderList['shopkeeperName']; ?>
                        </a>
                    </div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['userName']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['userAddress']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['userPhone']; ?></div>
                    <div class="col-sm-1 noPadding alignCenter">
                        <a href="<?php echo $this->url('admin_showdetails_coupons', array('id' => $orderList['couponId'])) ?>">
                            <?php echo $orderList['couponCode']; ?>
                        </a>
                    </div>
                    <div class="col-sm-1 noPadding alignCenter"><?php echo $orderList['couponDiscount']; ?></div>
                </div>
            </div>
            <?php $i++;
        }
    } else {
        ?>
        <div class="row pd5">
            <div class="col-sm-12">No Orders To Display</div>
        </div>
        <?php
    }
    ?>
</div>
