<?php
echo $this->partial('menu', array('active' => 'products'));
$form->setAttribute('action', $this->url('admin_add_products'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<label class="alert-danger"></label>

<div class="wrapper">
    <div class="panel panel-info pd20" >

        <div class="row">
            <div class ="col-sm-3">
                <label>Product Name *:</label>
                <?php echo $this->formElement($form->get('name')); ?>
                <span class="alert-danger"><?php echo $this->formElementerrors($form->get('name')); ?></span>
            </div>
            <div class ="col-sm-3">
                <label>Product Stock :</label>
                <?php echo $this->formElement($form->get('stock')); ?>
            </div>
            <div class ="col-sm-3">
                <label>Product Rent :</label>
                <?php echo $this->formElement($form->get('rent')); ?>
            </div>
            <div class ="col-sm-3">
                <label>Product Security :</label>
                <?php echo $this->formElement($form->get('security')); ?>
            </div>

        </div>
        <div class="row">
            <div class ="col-sm-3">
                <label>Category :</label>
                <?php echo $this->formElement($form->get('category')); ?>
            </div>
            <div class ="col-sm-3">
                <label>Gender:</label>
                <?php echo $this->formElement($form->get('gender')); ?>
                <span class="alert-danger"><?php echo $this->formElementerrors($form->get('gender')); ?></span>
            </div>
            <div class ="col-sm-3 select-check">
                <label>Product Size *:</label>
                <?php echo $this->formElement($form->get('size')); ?>
            </div>
            <div class ="col-sm-3">
                <label>Product Waist:</label>
                <?php echo $this->formElement($form->get('waist')); ?>
            </div>
        </div>

        <div class="row">
            <div class ="col-sm-3">
                <label>Product Image:</label>
                <?php echo $this->formElement($form->get('image')); ?>
                <span class="alert-danger"><?php echo $this->formElementerrors($form->get('image')); ?></span>
            </div>
            <div class ="col-sm-9">
                <label>Details *:</label>
                <?php echo $this->formElement($form->get('description')); ?>
                <span class="alert-danger"><?php echo $this->formElementerrors($form->get('description')); ?></span>
            </div>

        </div>
          <a href="<?php echo $this->url('admin_view_products');?>" class="btn btn-warning">Back</a>
        <?php echo $this->formRow($form->get('submit')); ?>

    </div>
</div>

<?php echo $this->form()->closeTag(); ?>
