<?php
echo $this->partial('menu', array('active' => 'products'));
?>
<div class="container pd20">
    <div class="panel panel-info col-md-12 pd20">
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-3">
                    <label> Name</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php echo wordwrap($product->getProductName(), 65, "<br>\n", true); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Category </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5 word-wrap">
                    <?php echo $product->getProductCategory(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Rent</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php
                        echo $product->getProductRent();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Security </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductSecurity(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Size </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductSize(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Stock </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductStock(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Actual Cost </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductActualcost(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Brand </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductBrand(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Designer </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductDesigner(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Occassion </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductOccassion(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Color </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductColor(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Available from </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductFromdate(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Available To </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductTodate(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Seo tags </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductSeotags(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Description </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $product->getProductDescription(); ?>
                </div>
            </div>
        </div>
        <div class="col-md-5 alignCenter">
            <?php
            $productImage = $product->getProductImage();
            if (empty($productImage)) {
                $productImage = 'default.png';
            }
            ?>
            <img src="<?php echo '/upload/Products/' . $productImage; ?>" height="auto" width="100%">
        </div>
    </div>
</div>
<div class="row col-md-3 col-md-offset-4">
    <a href="<?php echo $this->url('admin_view_products');?>" class="btn btn-primary btnWidth">Back</a>
    <a href="<?php echo $this->url('admin_edit_products', array('id' => $product->getProductId()));?>"
       class="btn btn-warning btnWidth">Edit</a>

</div>
