<div class="alert alert-dismissable alert-danger tour hidden"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button><ul><li></li></ul></div>
<?php echo $this->partial('menu', array('active' => 'tour')); ?>
<div class="row addButtonClass">
    <div class="col-sm-2">
        <a class="margin10"
           href="<?php echo $this->url('admin_add_products'); ?>">
            <button class="btn-primary btn">Add Products</button>
        </a>
    </div>
    <div class="col-sm-5">
        <form action="#" method="post">
            <select class="form-control col-sm-7" name="sortby" style="width:50%; margin-right: 10px">
                <option vlaue="">Sort by Rent</option>
                <option value="DESC">High to low</option>
                <option value="ASC">Low to high</option>
            </select>
            <input type="submit" value="Sort" class="col-sm-4 btn btn-primary">
        </form>
    </div>
    <div class="col-sm-5">
        <form action="#" method="post">
            <input type="text" name="productName" class="form-control col-sm-8" Placeholder="Search by name"  style="width:50%; margin-right: 10px">
            <input type="submit" value="Search" class="col-sm-4 btn-primary btn">
        </form>
    </div>
</div>
<div class="row itineraryRowHeading">
    <div class="col-sm-12 itineraryHeading">
        <div class="col-sm-2 noPadding">Products Name</div>
        <div class="col-sm-2 noPadding">Image</div>
        <div class="col-sm-2 noPadding">Category</div>
        <div class="col-sm-2 noPadding">Rent</div>
        <div class="col-sm-4 alignCenter">Action</div>
    </div>
</div>
<div class="">
    <?php
    $i = 1;
    if (count($this->products) > 0) {
        foreach ($this->products as $products) {
            ?>
            <div class="row attractionList widthNarrow ">
                <div class="col-sm-12 post itineraryList <?php if($i%2==0) {echo "greyColor";}?>">
                    <div class="col-sm-2 attrName"><?php echo $products['aufriProductsName']; ?></div>
                    <div class="col-sm-2 attrName"><img src="/upload/Products/<?php echo $products['aufriProductsImageIdFk']; ?>" height="80" width="100" ></div>
                    <div class="col-sm-2 noPadding"><?php echo $products['aufriProductsCategory']; ?> </div>
                    <div class="col-sm-2 noPadding"><?php echo $products['aufriProductsRent']; ?> </div>
                    <div class="col-sm-4">
                        <a class="margin25" href="<?php echo $this->url('admin_showdetails_products', array('id' => $products['aufriProductsId'])) ?>">
                            <button type="button" class="btn btn-success btnWidth" role="button">View</button></a>
                        <a href="<?php echo $this->url('admin_edit_products', array('id' => $products['aufriProductsId'])) ?>">
                            <button type="button" class="btn btn-warning btnWidth">Edit</button></a>
                        <a href="<?php echo $this->url('admin_delete_products', array('id' => $products['aufriProductsId'])) ?>">
                            <button type="button" class="btn btn-danger btnWidth">Delete</button></a>
                    </div>
                </div>
            </div>
            <?php $i++;
        }
    } else {
        ?>
        <div class="row pd5">
            <div class="col-sm-12">No Products To Display</div>
        </div>
        <?php
    }
    ?>
</div>
