<!-- Nav tabs -->
<?php echo $this->partial('menu', array('active' => 'home')); ?>
<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
        <h2>Welcome  Admin</h2>
    </div>
    <h4>
        Today Order: <?php echo count($todaysOrder);?>
    </h4>
    <h4>
        Total Order: <?php echo count($totalOrders);?>
    </h4>
    <h4>
        Our Inventory: <?php echo count($totalProducts); ?>
    </h4>
    <h4>
        Out of Stock: <?php echo count($outOfStockProducts); ?>
    </h4>
</div>
