<?php
/**
 * menu page to display menu options at the top of the page
 * @author Deepika Verma <deepika.verma@optimusinfo.com>
 */
?>
<div class="wrapper">
    <div class="alignLeft">

        <h1>Admin Panel</h1>
    </div>
</div>

<div class="alignRight">
    <div class="dropdown">
        <button class="btn btn-default dropdown-toggle rightMargin" type="button" id="menu1" data-toggle="dropdown">
            <a role="menuitem" tabindex="-1" href="<?php echo $this->url('auth_logout'); ?>">Logout</a></button>
    </div>
</div>


<!-- Nav tabs -->


<?php
    echo $this->navigation('Zend\Navigation\Admin')->menu()
            ->setUlClass('nav nav-tabs')
            ->setAddClassToListItem(true)
            ->render();
?>
