<?php
echo $this->partial('menu', array('active' => 'products'));
?>
<div class="container pd20">
    <div class="panel panel-info col-md-12 pd20">
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-3">
                    <label> Name</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php echo wordwrap($shopkeeper->getShopkeeperName(), 65, "<br>\n", true); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Email </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5 word-wrap">
                    <?php echo $shopkeeper->getShopkeeperEmail(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Phone no</label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-5">
                    <?php
                        echo $shopkeeper->getShopkeeperPhone();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>City </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $address->getAddressCity(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Pincode </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $address->getAddressPincode(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>LandMark </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $address->getAddressLandmark(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Address </label>
                </div>
                <div class="col-md-1">
                    <label>: </label>
                </div>
                <div class="col-md-8 word-wrap">
                    <?php echo $address->getAddressAddress(); ?>
                </div>
            </div>


        </div>
    </div>
</div>
<div class="row col-md-3 col-md-offset-4">
    <a href="<?php echo $this->url('admin_view_shopkeepers');?>" class="btn btn-primary btnWidth">Back</a>
    <a href="<?php echo $this->url('admin_edit_shopkeepers', array('id' => $shopkeeper->getShopkeeperId()));?>"
       class="btn btn-warning btnWidth">Edit</a>

</div>
