<div id="search">
	<form id="find-member" class="form-horizontal">
		<p>Search for a member by one of these options:</p>

		<div class="row-fluid">
			<div class="span6">
				<div class="control-group">
					<label for="first" class="control-label">First Name:</label>

					<div class="controls">
						<input id="first" name="member_first_name" type="text" autofocus>
					</div>
				</div>
				<div class="control-group">
					<label for="email" class="control-label">Email Address:</label>

					<div class="controls">
						<input id="email" name="member_email" type="email">
					</div>
				</div>
				<div class="control-group">
					<label for="company" class="control-label">Company Name:</label>

					<div class="controls">
						<input id="company" name="member_company" type="text">
					</div>
				</div>
				<div class="control-group">
					<label for="postal" class="control-label">Zip/Postal Code:</label>

					<div class="controls">
						<input id="postal" name="member_zip" type="text">
					</div>
				</div>
			</div>
			<!--/span-->

			<div class="span6">
				<div class="control-group">
					<label for="last" class="control-label">Last Name:</label>

					<div class="controls">
						<input id="last" name="member_last_name" type="text">
					</div>
				</div>
				<div class="control-group">
					<label for="account" class="control-label">Account Number:</label>

					<div class="controls">
						<input id="account" name="member_account" type="text" required>
					</div>
				</div>
				<div class="control-group">
					<label for="province" class="control-label">State:</label>

					<div class="controls">
						<select id="province" name="member_state">
							<option selected value="">Select</option>
							<option value="AK">Alaska</option>
							<option value="AL">Alabama</option>
							<option value="AR">Arkansas</option>
							<option value="AZ">Arizona</option>
							<option value="CA">California</option>
							<option value="CO">Colorado</option>
							<option value="CT">Connecticut</option>
							<option value="DC">District of Columbia</option>
							<option value="DE">Delaware</option>
							<option value="FL">Florida</option>
							<option value="GA">Georgia</option>
							<option value="HI">Hawaii</option>
							<option value="IA">Iowa</option>
							<option value="ID">Idaho</option>
							<option value="IL">Illinois</option>
							<option value="IN">Indiana</option>
							<option value="KS">Kansas</option>
							<option value="KY">Kentucky</option>
							<option value="LA">Louisiana</option>
							<option value="MA">Massachusetts</option>
							<option value="MD">Maryland</option>
							<option value="ME">Maine</option>
							<option value="MI">Michigan</option>
							<option value="MN">Minnesota</option>
							<option value="MO">Missouri</option>
							<option value="MS">Mississippi</option>
							<option value="MT">Montana</option>
							<option value="NC">North Carolina</option>
							<option value="ND">North Dakota</option>
							<option value="NE">Nebraska</option>
							<option value="NH">New Hampshire</option>
							<option value="NJ">New Jersey</option>
							<option value="NM">New Mexico</option>
							<option value="NV">Nevada</option>
							<option value="NY">New York</option>
							<option value="OH">Ohio</option>
							<option value="OK">Oklahoma</option>
							<option value="OR">Oregon</option>
							<option value="PA">Pennsylvania</option>
							<option value="PR">Puerto Rico</option>
							<option value="RI">Rhode Island</option>
							<option value="SC">South Carolina</option>
							<option value="SD">South Dakota</option>
							<option value="TN">Tennessee</option>
							<option value="TX">Texas</option>
							<option value="UT">Utah</option>
							<option value="VA">Virginia</option>
							<option value="VT">Vermont</option>
							<option value="WA">Washington</option>
							<option value="WI">Wisconsin</option>
							<option value="WV">West Virginia</option>
							<option value="WY">Wyoming</option>
						</select>
					</div>
					<!--/.controls-->
				</div>
			</div>
			<!--/span-->
		</div>
		<!--/row-->
	</form>
	<!--#find-member-advanced.form-horizontal-->
</div>
<div id="searchResults"></div>
<div class="pull-right">
	<a class="btn btn-primary btn-large" id="findMbr"
		data-loading-text="Finding..." data-complete-text="Go Back"
		href="javascript:">Find</a>
</div>
