<section class="content-top-margin page-title page-title-small bg-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-12 wow fadeInUp" data-wow-duration="300ms">
                <!-- page title -->
                <h1 class="black-text">Hey! Your Order placed SuccessFully</h1>

                <h1 class="black-text">Your Order Id is <?php echo $orderId; ?></h1>
                <!-- end page title -->
            </div>
            <div class="col-lg-4 col-md-5 col-sm-12 breadcrumb text-uppercase wow fadeInUp xs-display-none" data-wow-duration="600ms">
                <!-- breadcrumb -->
                <ul>
                    <li><a href="<?php echo $this->url('home');?>">Home</a></li>
                </ul>
                <!-- end breadcrumb -->
            </div>
        </div>
    </div>
</section>
